travis:
  secure:
    BINSTAR_TOKEN: AUyVmmWFy7mRRO2o1HaV1c/wBCfqzCkcl20bRe4bpy7fI2lXI1gJdUNnhGeLPoMN4XmYNVbzNJCe/QBjenQBk1ZrhrZ39g/ZP7xmvQupeCfwK2Zc80jeUU4nyaB/RuWW3I+6Gwzw39308xsx8/98g09BF9r4l6wAuGcvxaUmIjgNY288YiBHDYmeYWJMLNjBelBY0ogeL2aRrbzfrOjX5qJ6st4+tI8GN9sYRtHVS1eqi7EXw9JvfCzb7HFIkAogQKROMKjc3Lwn6937vGz6TGLKgLNI7s8FzdvSplNJo2uP3tExGeIKL9NmgHg8c52hFdUi84ztf5sVh66QZq8rTVr3ZwKh+rvrsEH6BuX12AJj2k5oDAD+l/wgqduy1R2vv36FtvH+oy2sFHKXGIT1lRwHZC84JpSU8mr+ODnk210c7zQbcqu4+wYXEc1jWR3OfUIU6bjCa+CpIZQ9hb8Gh86QSZlY4Rihyu8wvLSNDAGUWGOGrQiuz2hW+lX5VpeaHOcVcrRiOS09DwfEAnF/ooPmaJIjKbyR6pc7iZqGDnIO42Plt466C5zt4CYQY6N2Zf0uwcHQahyg3ocwEiOszhzBeF9884q6DRfHLMvrVsRmWfPtEBva6x8lcBZWTguzc6vL1IdOY/G+NtXFO2kdBz8tAngC9LEE6SiwgZfxJD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
